### ISSUE TITLE
onnx models cannot be downloaded

### ISSUE THREAD

**Issue by 666zachary** [hamdiboukamcha/SPEED-SAM-C-TENSORRT#1]
Thank you for your excellent work, I would like to deploy it on my computer and hopefully download the onnx models!

**Comment by xiangw369** [comment]
> Thank you for your excellent work, I would like to deploy it on my computer and hopefully download the onnx models!

Did you get these two onnx files? Can you share it? thank you very much.

**Comment by hamdiboukamcha** [comment]
It's done! We have uploaded the ONNX file to the project. Enjoy!
