### ISSUE TITLE
How to load other onnx models

### ISSUE THREAD

**Issue by Yin0120** [hamdiboukamcha/SPEED-SAM-C-TENSORRT#4]
I want to use other onnx models such as vit_b, mobile_sam, etc., but I get an error when loading directly, please can I use the above model. What can I do if I can
<img width="557" alt="36a490a00bffb9eccb724fa37cdb481" src="https://github.com/user-attachments/assets/ca4db360-b9be-45d6-b4b8-e52f4c21b0ce">

**Comment by hamdiboukamcha** [comment]
The error indicates that your ONNX model has INT64 weights, which TensorRT does not support natively.
You can convert INT64 weights to INT32 or FP16 as follows:
Use the [ONNX Graph Surgeon](https://docs.nvidia.com/deeplearning/tensorrt/onnx-graphsurgeon/), part of NVIDIA's TensorRT, to edit and fix the model before loading.
Convert the model to FP16 precision using tools like onnx-simplifier or Python
