### ISSUE TITLE
Performance environment (Question)

### ISSUE THREAD

**Issue by arielkantorovich** [hamdiboukamcha/SPEED-SAM-C-TENSORRT#5]
Hi, 
Thank you for sharing your work, I see the impressive results of 12ms, and I would like to know which hardware you use in inference time.
In addition, you can try to estimate the inference time on Jetson Xavier NX (21 TFLOPs). Can this work run in real-time, for example, 30FPS on Xavier NX?

**Comment by hamdiboukamcha** [comment]
Sorry, we don’t have this card to approve this benchmark time
